from tgaoi.aoi import (
    softmax_graph,
    rmsnorm_graph,
    linear_graph,
    attention_graph,
    adam_graph,
    activation_graph,
    layernorm_graph,
    conv2d_graph,
    patch_embedding_graph,
    vit_self_attention_graph,
    vit_mlp_graph,
    vit_block_graph,
    convx_graph,
    bottleneck_graph,
    c2f_graph,
    multiscale_projector_graph,
    dino_backbone_graph,
    bilinear_sampler_graph,
    ms_deform_attention_graph,
    detection_mlp_graph,
    detr_decoder_layer_graph,
    detr_decoder_graph,
    hybrid_encoder_graph,
    rfdetr_graph,
    box_iou_graph,
    hungarian_matcher_graph,
    detr_set_criterion_graph,
)


def test_starter_aois_validate():
    graphs = [
        softmax_graph(),
        rmsnorm_graph(),
        linear_graph(),
        attention_graph(),
        adam_graph(),
        activation_graph("relu"),
        layernorm_graph(),
        conv2d_graph(),
        patch_embedding_graph(),
        vit_self_attention_graph(),
        vit_mlp_graph(),
        vit_block_graph(),
        convx_graph(),
        bottleneck_graph(),
        c2f_graph(),
        multiscale_projector_graph(),
        dino_backbone_graph(),
        bilinear_sampler_graph(),
        ms_deform_attention_graph(),
        detection_mlp_graph(),
        detr_decoder_layer_graph(),
        detr_decoder_graph(),
        hybrid_encoder_graph(),
        rfdetr_graph(),
        box_iou_graph(),
        hungarian_matcher_graph(),
        detr_set_criterion_graph(),
    ]
    for graph in graphs:
        graph.validate()
        assert graph.outputs
